spring:
  application:
    name: www

  thymeleaf:
    suffix: .html

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-3-131-93-152.us-east-2.compute.amazonaws.com:3306/traverse?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: user1
    password: traverse
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      validation-timeout: 2000
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000


server:
  servlet:
    session:
      tracking-modes: cookie
      
        
